services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - "80:80"
    volumes:
      - ..:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf

  phpfpm:
    image: php:8.3-fpm-alpine
    volumes:
      - ..:/app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456